general:
  data_dir: src/data
  log_level: DEBUG
  prompt:
    include_conversation_history: true
    include_knowledge_context: false
local:
  enabled: false
  ollama:
    base_url: http://host.docker.internal:11434
    cache_dir: null
    cache_enabled: false
    cache_ttl: 86400
    default_model: deepseek-r1:latest  # Use the correct model name with version
    log_interval: 100
    max_cache_entries: 1000
    max_cache_size_mb: 100
    max_tokens: 500
    temperature: 0.7
hosted:
  enabled: true
  bedrock:
    default_model: amazon.nova-micro-v1:0
    max_tokens: 1000
    models:
      default: amazon.nova-micro-v1:0
    region_name: us-east-1
    temperature: 1.0
    timeout: 30
  prompt_optimizer:
    avg_chars_per_token: 4
    enabled: true
    max_prompt_tokens: 800
    # system_prompt: You are a helpful bilingual dog companion in a Japanese train station.
    #   Assist with language help, directions, and cultural information. Provide clear
    #   and helpful explanations.
  usage_tracker:
    auto_save: true
    cost_per_1k_input_tokens:
      amazon.nova-micro-v1:0: 0.0003
      amazon.titan-text-express-v1: 0.0008
      anthropic.claude-3-haiku-20240307-v1:0: 0.00025
      anthropic.claude-3-sonnet-20240229-v1:0: 0.003
      default: 0.001
    cost_per_1k_output_tokens:
      amazon.nova-micro-v1:0: 0.0006
      amazon.titan-text-express-v1: 0.0016
      anthropic.claude-3-haiku-20240307-v1:0: 0.00125
      anthropic.claude-3-sonnet-20240229-v1:0: 0.015
      default: 0.002
    daily_token_limit: 100000
    enabled: true
    hourly_request_limit: 100
    monthly_cost_limit: 50.0
    storage_path: src/data/usage/bedrock_usage.json 